function K = davenport_matrix(B)
  % Compute the Davenport Matrix, K, given the attitude profile matrix, B
  z = [ ...
    B(2, 3) - B(3, 2); ...
    B(3, 1) - B(1, 3); ...
    B(1, 2) - B(2, 1) ...
    ];
  trB = trace(B);
  K1 = [ ...
    B + B' - trB * eye(3); ...
    z' ...
    ];
  K2 = [z; trB];
  K = [K1, K2];
end
